argo-cd:
  dex:
    enabled: false
  global:
    priorityClassName: system-cluster-critical
  server:
    extraArgs:
      - --insecure
    config:
      statusbadge.enabled: "true"
      resource.customizations.health.argoproj.io_Application: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: true
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
